nc1z/Asset-Screener-App

client/index.html, client/src/App.jsx, client/src/index.css, client/src/routes/Login.jsx, client/src/routes/Signup.jsx, client/tailwind.config.cjs
- Updated Login and Signup pages with JSX/HTML
- Added styling globally, as well as Tailwind classes for Login/Signup components
- Updated overall routing
- Added Links/Navigation for Login/Signup pages
=> [Login, Signup, CSS] Created Login and Signup Pages and Edited Global Styling

client/src/components/UpdateUserForm.jsx, client/src/routes/Account.jsx
- Created form component for "Account" route
- Added placeholders text and functions
=> [UpdateUserForm] Created Form Component for Updating, Edited readonly

client/src/components/Navbar.jsx
- Updated Navbar menu items to close menu when clicked
=> [Navbar] Updated onClick menu items to close menu

client/src/components/Navbar.jsx
- Updated logout logic with navigation to login page
=> [Navbar] Updated logout logic with navigation

client/src/routes/Login.jsx, client/src/routes/Signup.jsx
- Updated input field with min length attribute of 8.
=> [Login, Signup] Updated password field minlength 8

client/src/routes/Login.jsx, client/src/routes/Signup.jsx
- Included 'required' attribute to input fields
=> [Login, Signup] Make input fields required

README.md, client/src/App.jsx, client/src/components/ErrorMessage.jsx, client/src/components/Navbar.jsx, client/src/components/TicketForm.jsx, client/src/components/Watching.jsx, client/src/routes/Portfolio.jsx, client/src/routes/Ticket.jsx, client/src/routes/Watchlist.jsx
- Added Portfolio routes and components + base template
- Added Ticket route, form and component, linking it to Portfolio
- Added Watchlist routes and components + base template (table)
- Updated README.md
=> [Portfolio, Navlinks, Watchlist, Ticket, README] Created new components and updated routes

client/src/components/UpdateUserForm.jsx
- Changed readonly attribute on form input to readOnly
=> [UpdateUserForm] refactor code

client/src/App.jsx, client/src/ProtectRoute/ProtectedRoute.jsx, client/src/components/Dashboard.jsx, client/src/components/ErrorDisplay.jsx, client/src/components/ErrorMessage.jsx, client/src/components/Navbar.jsx, client/src/context/AuthContext.jsx, client/src/context/UserContext.jsx, client/src/routes/Login.jsx, client/src/routes/Signup.jsx
- Added AuthContext and wrapped app in context (Now every route has access to the user details once authenticated)
- Login, Signup logic + axios handling
- Misc refactoring of input minLength
- Updated ProtectedRoutes component and wrapped private routes
=> [AuthContext, Login, Signup, ProtectedRoutes, Error Handling]

server/src/middleware/checkAuth.js, server/src/routes/auth.js
-edited endpoints return json from errors to error
=> refactored errors to error

server/package-lock.json, server/package.json, server/src/routes/details.js
-portfolio updating done
-portfolio endpoint testing & error handling done
-tested in MongoDB
=> [portfolio updating] endpoint completed and tested

client/src/App.jsx, client/src/components/Navbar.jsx, client/src/components/PortfolioTable.jsx, client/src/components/UpdateUserForm.jsx, client/src/components/UserDetails.jsx, client/src/components/Watching.jsx, client/src/main.jsx, client/src/routes/Portfolio.jsx
- Updated Navbar to display user email
- Added comments in App.jsx routes to weigh pros and cons of protectedRoute wrapping all once versus wrapping each individually
- Shifted AuthContext wrapper to main.jsx so App.jsx can use global context states (for visibility of Navbar, redirect auth routes..)
- Refactored watchlist page so it doesn't display a loading screen perpetually
- Completed all logic and covered edge cases for portfolio page.
=> [Navbar, App.jsx, Main, Account, Watchlist, Portfolio] Updates, refactoring and New Components

server/src/middleware/checkAuth.js, server/src/models/User.js, server/src/models/portfolio.js, server/src/models/watchlist.js, server/src/routes/auth.js, server/src/routes/details.js, server/src/routes/markets.js, server/src/server.js
-prettier formatting done
-watchlist updating endpoint done and tested
-watchlist delete endpoint done and tested
=> prettier formatting done

.gitignore, package.json, server/package.json
- `npm init -y` in root folder
- Added package.json start scripts
- Edited server folder package.json scripts for production
=> [Deployment] configure package.json and init root package for cyclic

server/src/routes/auth.js
=> [deployment] resolving import errors in auth.js

client/src/components/Dashboard.jsx, client/src/components/PortfolioTable.jsx, client/src/components/Saved.jsx, client/src/components/TicketForm.jsx, client/src/components/TicketHistory.jsx, client/src/components/Watching.jsx, client/src/context/AuthContext.jsx, client/src/routes/Login.jsx, client/src/routes/Signup.jsx
Updated localhost8080 links with 
https://good-gray-dugong-yoke.cyclic.app/
=> [Api Links] Updated endpoints with live server link

README.md
- Readme updated with brief app description and image screenshots
=> [Readme] readme updated with app description and image snippets

client/src/components/TicketForm.jsx, client/src/routes/Login.jsx, client/src/routes/Signup.jsx
Issue #38 resolved
- Disabled login/signup button when clicked
- Additionally, disabled ticket form button with the same logic as well
=> Issue #38: Resolved

server/src/routes/details.js
- Added asset type validation
- Added input type validation
- Added order amount validation
=> issue #41 resolved - extra form validation added

server/src/routes/details.js
- Changed from typeof to isNaN
=> issue #41 refactored form validation

README.md
- Added wireframe images to Readme file
=> [readme] issue #27 - updated with wireframe images

server/src/routes/markets.js
- Added pagination logic to backend
=> issue #42 added pagination logic to backend

server/src/routes/markets.js
- Added logic to prevent users from displaying negative page numbers
=> refactored pagination logic
